BridgePatternExample::Correct::Shape
IColorImplementation BridgePatternExample.Correct.Shape._colorImplementation
Referenced by BridgePatternExample.Correct.Shape.Shape, BridgePatternExample.Correct.Shape.DrawPixel.
const int BridgePatternExample.Correct.Shape._size
Referenced by BridgePatternExample.Correct.Shape.Shape, BridgePatternExample.Correct.Shape.DepictInConsole, BridgePatternExample.Correct.Circle.Draw, BridgePatternExample.Correct.Square.Draw.
ConsoleColor [,] BridgePatternExample.Correct.Shape._drawing
Referenced by BridgePatternExample.Correct.Shape.Shape, BridgePatternExample.Correct.Shape.DrawPixel, BridgePatternExample.Correct.Shape.DepictInConsole.
BridgePatternExample.Correct.Shape.Shape(IColorImplementation colorImplementation)
References BridgePatternExample.Correct.Shape._colorImplementation, BridgePatternExample.Correct.Shape._drawing, BridgePatternExample.Correct.Shape._size.
void BridgePatternExample.Correct.Shape.DrawPixel(int x, int y)
References BridgePatternExample.Correct.Shape._colorImplementation, BridgePatternExample.Correct.Shape._drawing, BridgePatternExample.Correct.IColorImplementation.Color.
Referenced by BridgePatternExample.Correct.Circle.Draw, BridgePatternExample.Correct.Square.Draw.
abstract void BridgePatternExample.Correct.Shape.Draw()
Referenced by BridgePatternExample.Correct.Shape.DepictInConsole.
void BridgePatternExample.Correct.Shape.DepictInConsole()
References BridgePatternExample.Correct.Shape._drawing, BridgePatternExample.Correct.Shape._size, BridgePatternExample.Correct.Shape.Draw.